#Tomcat端口
server:
  port: 8080

#上传文件大小限制
spring:
  servlet:
    multipart:
      max-file-size: "10MB"
      max-request-size: "100MB"
  redis:
    password: "luat"
    host: "127.0.0.1"
    port: 6379

#log等级
logging:
  level:
    root: "debug"
  file:
    name: "log.txt"

#ssl配置
#server.ssl.key-store=classpath:server.key.p12
#server.ssl.key-store-password=Jeremy
#server.ssl.key-alias=server
#server.ssl.keyStoreType=JKS
